### PR TITLE
Issues/367 support fullhalf

### PR DESCRIPTION
**Pull request by making**
#367 please review

### CODE REVIEW

**Comment by ikeyat** [comment]
I checked. It looks OK.

@kazuki43zoo 
Please review and merge if you have no comment.
Your #424 needs to be fixed for this change (terasoluna-gfw-string).

**Comment by btshimizukza** [comment]
@making 

I've checked this PR. Please check review comments and reflect these if feel the need.

**Comment by btshimizukza** [comment]
@ikeyat 

> Your #424 needs to be fixed for this change (terasoluna-gfw-string).

It's OK.

**Comment by making** [comment]
@btshimizukza 
Fixed review comments

**Comment by btshimizukza** [comment]
@making 
I've checked and added a new comment.
Please refer to https://github.com/terasolunaorg/terasoluna-gfw/commit/181827b66a6ae6758df8457d6ad7738fd3dcc784#commitcomment-14917135 .

**Pull request merged**
