### PR TITLE
spring boot 2.2.12 #1046

### PR DESCRIPTION
**Pull request by btkatoufm**
Please review #1046.

### CODE REVIEW

**Review by yoshikawaa — COMMENTED** [review]
You can remove 2 commit about Joda-Time. Please re-push this branch.

**Comment by yoshikawaa** [comment]
The version of Joda-Time on which 5.6.2 depends is newer than 5.7.0. Consider updating 5.7.0.

**Comment by btkatoufm** [comment]
https://github.com/terasolunaorg/terasoluna-gfw/pull/1058#issuecomment-765117869
I created an Issue with #1059.

**Comment by btkatoufm** [comment]
https://github.com/terasolunaorg/terasoluna-gfw/pull/1058#pullrequestreview-573947856
I re-pushed to remove unnecessary commits.

**Review by btkobayashirun — APPROVED** [review]

**Pull request merged**
