### PR TITLE
upgrade to spring io platform Cairo-SR1. #810

### PR DESCRIPTION
**Pull request by btournc**
Please review #810
terasoluna-gfw / terasoluna-gfw-parent / pom.xml in Line 395
Change io.spring.platform.version from "Brussels-SR 5" to "Cairo-SR 1".

### CODE REVIEW

**Comment by yoshikawaa** [comment]
@btournc 
Pleaes investigate the fact that the version of jadira-usertype to select depends on the version of Hibernate JPA being updated.

**Comment by kazuki43zoo** [comment]
> The following OSS's versions should be changed acording to Spring IO Platform upgrade.

I think the mybatis and dozer not depend on Spring IO PF Cairo. And the tomcat depend on Tomcat 8.5.x rather than 9.0.x on Spring IO PF Cairo(Spring Boot 2.0.x).

**Comment by yoshikawaa** [comment]
Thanks, agree with @kazuki43zoo .
We recognize that MyBatis3 & Dozer versions are not related to Spring IO.
I think that we should change them in another Issue or change the position (title) of this Issue.

@kazuki43zoo 
Since A environment will become Tomcat 9, we want to use Tomcat 9 in Maven Cargo Plugin.
I think that it's one valid way as follows.
* terasoluna-gfw -> depends on Spring IO Cairo (Tomcat 8.5)
* functional tests & sample applications -> re-depends on A environment (Tomcat 9)

Do you have any good ideas?

**Comment by btournc** [comment]
@yoshikawaa  @hirakuriy 
Fixed  version of java and jadira with below. 
MyBatis3 and dozer versions will be fix in another issue.
Tomcat depends on Spring IO Cairo (Tomcat 8.5).
 3e9abcf8a4fb15ef01456f9018f0ae070c71fc8e

**Comment by hirakuriy** [comment]
@kazuki43zoo @btournc 
As a result of discussion with @yoshikawaa , we decided to make terasoluna-gfw depend on A-environment(Tomcat 9.0.6) even though tomcat depends on 8.5.x on Spring IO PF Cairo, because that is more simple way than the way of re-depending on A-environment at blank project and other applications.

@btournc 
Fixing versions of java, jadira, and Spring IO PF is OK.
Please fix versions of MyBatis, dozer, and Tomcat in another issue.

**Comment by hirakuriy** [comment]
@yoshikawaa 
I think you're quite right.
So I'll restore branch, @btournc , please fix version of Tomcat in this issue.

**Comment by hirakuriy** [comment]
@btournc 
Due to the version up of Spring IO PF, some compilation error was happend in testcase.
Please fix it.

Please see below error log.
https://travis-ci.org/terasolunaorg/terasoluna-gfw/jobs/390640415#L802

**Comment by kazuki43zoo** [comment]
Why merged this PR on build error occurred ?

**Comment by yoshikawaa** [comment]
@kazuki43zoo 
It seems like that merged without noticing build errors.
(The administrator can ignore the build status and merge.)

We reverted merge commits and resolving errors, thanks.

**Comment by kazuki43zoo** [comment]
> (The administrator can ignore the build status and merge.)

Oh...

**Pull request merged**
