### PR TITLE
fixed Sonar Qube alerts #428

### PR DESCRIPTION
**Pull request by btfurukawatkr**
Please review #428.
- Fixed code for SonarQube alerts.
- Checked some alert-issues as 'won't fix' since it looked fine with the existing code and can rather get messy by fixing the code.
- left some alert-issues unfixed(all the same issue saying "more branches need to be covered by unit tests to reach the minimum threshold of 65.0% branch coverage.")

### CODE REVIEW

**Comment by ikeyat** [comment]
@btfurukawatkr 
Please check why coverage went down and confirm the decrease of coverage is proper.

**Comment by btfurukawatkr** [comment]
@ikeyat 

I've checked why the coverage has decreased, and confirmed that  there is no problem.
Here's a breif summary below.

1. added writeObject/readObject method for serialization/deserialization to fix alert 'Make "xxx" transient or serializable.'. So number of missed-lines increased.
 * terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
 * terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
 * terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java

2. added a private constructor which is not used
 * terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ConstraintValidatorsUtils.java
 * terasoluna-gfw-string/src/main/java/org/terasoluna/gfw/common/fullhalf/DefaultFullHalf.java

3. refactored some code-lines to extract to a method, so number of missed-lines increased and percentage has decreased
 * terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptor.java

4. fixed code 'String msg = null;" to "String msg;" and coveralls skipped the line and marded as not covered
 * terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessageUtils.java

**Comment by ikeyat** [comment]
@btfurukawatkr 

> added writeObject/readObject method for serialization/deserialization to fix alert 'Make "xxx" transient or serializable.'. So number of missed-lines increased.

 - [ ] Unit tests should be added for added method.

Others look reasonable.

**Comment by ikeyat** [comment]
Please backport 5.0.x

**Pull request merged**
